[symbols]

[symbols.tecken]
name = "Mozilla Symbols Server"
environment_stage = "https://tecken-stage.symbols.nonprod.webservices.mozgcp.net"
environment_prod = "https://symbols.mozilla.org"

[symbols.eliot]
name = "Mozilla Symbolication Service"
environment_stage = "https://eliot-stage.symbols.nonprod.webservices.mozgcp.net"
environment_prod = "https://symbolication.services.mozilla.com"


[socorro]

[socorro.antenna]
name = "Collector"
environment_stage = "https://crash-reports.allizom.org"
environment_prod = "https://crash-reports.mozilla.com"

[socorro.socorro]
name = "Socorro"
environment_stage = "https://crash-stats.allizom.org"
environment_prod = "https://crash-stats.mozilla.org"


[cloud-eng]

[cloud-eng.mzcld-demo]
name = "MozCloud Demo"
environment_stage = "https://stage.mzcld-demo.nonprod.webservices.mozgcp.net"
environment_prod = "https://prod.mzcld-demo.prod.webservices.mozgcp.net"

[cloud-eng.o11y-demo]
name = "o11y Demo"
environment_dev = "https://dev.o11y-demo.nonprod.sandbox.mozgcp.net/"
